### PR TITLE
chore: update README.md

### PR DESCRIPTION
**Pull request by moul**
add pkg.go.dev badge

### CODE REVIEW

**Comment by fgm** [comment]
I'd rather link to the overview page, at https://pkg.go.dev/github.com/bearer/go-agent?tab=overview : I always feel it is more welcoming as a entry point, don't you ?

**Comment by moul** [comment]
What's the difference between the overview tab and the README where the user will come from, isn't it the same content?

I personally read READMEs on GitHub and open pkg.go.dev to discover the package API

**Comment by fgm** [comment]
Personal preference, I guess: I feel that for newcoming users discovering a package, finding the same content in the destination site may be more reassuring than diving into the API immediately. YMMV.

**Review by didroe — APPROVED** [review]
Missed this PR sorry.

I think it makes sense to link directly to the API

**Pull request merged**
